# Generated by Django 4.1 on 2022-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="", upload_to="blog/images"),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
