# Generated by Django 4.1 on 2022-08-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_body_post_image_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image2",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="blog/images"),
        ),
    ]
