# Generated by Django 4.1 on 2022-08-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image2",
        ),
    ]
