# Generated by Django 4.1 on 2022-08-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(default="", upload_to="portfolio/images"),
        ),
        migrations.AddField(
            model_name="project",
            name="title",
            field=models.CharField(default="", max_length=100),
        ),
    ]
